export default {
    protocol: 'https',
    host: window.location.host,
    service: "config",
    rebasedurl:"scp/v1/rsv/rulesystemversion",
    contexturl:"scp/v1/rsv",
    messagefilterurl:"scp/v1/msgtracingconfig",
    contextListUrl:"scp/v1/msgfilter",
    slfconfigurationurl:"scp/v1/slfConfiguration",
    slflookupurl:"scp/v1/slfLookUp",
    destinationmapurl:"scp/v1/destinationMap",
    nfserviceurl:"scp/v1/nfService",
    nfprofileurl:"scp/v1/nfProfileMap",
    slfkeypairurl:"scp/v1/keyMapSet",
    thrprofileurl:"scp/v1/throttlingprofile",
    thrconfigurl:"scp/v1/throttlingconfig",
    peerconfigurl:"scp/v1/peerconfig",
    tracingFieldurl:"scp/v1/edrtracingconfig/getSupportedEdrFields",
    tracingProfileUrl:"scp/v1/tracingProfileConfigs",
    destNameUrl:"scp/v1/edrtracingconfig",
    traceByTypeProfileUrl:"scp/v1/edrtracingconfig/getProfNames",
    destcprofileurl:"scp/v1/tracingDestinationDetailsConfigs",
    delForDestinationConfig:"scp/v1/edrtracingconfig",
    delForTracingProfile:"scp/v1/edrtracingconfig/deleteProf",
    mediationurl:"scp/v1/mediationProfileConfigs",
    fieldconfigurl:"scp/v1/fieldDefinitionConfigs",
    probeStatus:"producerCache/allCache",
    staticGetOnNFtype:"scp/v1/peerNfConfig/fetchbulkprofiles",
    staticProf:"scp/v1/peerNfConfig"
}